### ISSUE TITLE
OOM when inferencing a long audio (4m48s)

### ISSUE THREAD

**Issue by hokamc** [Winfredy/SadTalker#229]
CUDA out of memory. Tried to allocate 5.27 GiB (GPU 0; 15.73 GiB total capacity; 6.50 GiB already allocated; 1.47 GiB free; 12.69 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by hokamc** [comment]
limiting the size works for me

`PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024`

**Comment by see2run** [comment]
does it sacrifice inference time? making it slower? or it still run at its usual inference speed?
